// Dette er filen som inneholder alle data om kort. De sorteres i separate lister og klasser.
package Database;

import java.util.Arrays;
import java.util.List;

public class Cards {
    //Sword & Shield - Brilliant Stars
    private static final List<String> cl_brilliant_stars = Arrays.asList(
            "001 Exeggcute",
            "002 Exeggutor",
            "003 Shroomish",
            "004 Breloom",
            "005 Tropius",
            "006 Turtwig",
            "007 Grotle",
            "008 Torterra",
            "009 Burmy",
            "010 Wormadam",
            "011 Mothim",
            "012 Cherubi",
            "013 Shaymin V",
            "014 Shaymin VSTAR",
            "015 Karrablast",
            "016 Zarude V",
            "017 Charizard V",
            "018 Charizard VSTAR",
            "019 Magmar",
            "020 Magmortar",
            "021 Moltres",
            "022 Entei V",
            "023 Torkoal",
            "024 Chimchar",
            "025 Monferno",
            "026 Infernape",
            "027 Simisear V",
            "028 Kingler V",
            "029 Kingler VMAX",
            "030 Staryu",
            "031 Lapras",
            "032 Corphish",
            "033 Crawdaunt",
            "034 Snorunt",
            "035 Piplup",
            "036 Prinplup",
            "037 Empoleon",
            "038 Buizel",
            "039 Floatzel",
            "040 Lumineon V",
            "041 Manaphy",
            "042 Cubchoo",
            "043 Beartic",
            "044 Eiscue",
            "045 Raichu V",
            "046 Electabuzz",
            "047 Electivire",
            "048 Raikou V",
            "049 Shinx",
            "050 Luxio",
            "051 Luxray",
            "052 Pachirisu",
            "053 Clefairy",
            "054 Clefable",
            "055 Starmie",
            "056 Mewtwo",
            "057 Granbull V",
            "058 Baltoy",
            "059 Claydol",
            "060 Duskull",
            "061 Dusclops",
            "062 Dusknoir",
            "063 Chimecho",
            "064 Whimsicott V",
            "065 Whimsicott VSTAR",
            "066 Sigilyph",
            "067 Dedenne",
            "068 Mimikyu V",
            "069 Mimikyu VMAX",
            "070 Milcery",
            "071 Alcremie",
            "072 Hitmontop",
            "073 Nosepass",
            "074 Trapinch",
            "075 Vibrava",
            "076 Flygon",
            "077 Wormadam",
            "078 Riolu",
            "079 Lucario",
            "080 Throh",
            "081 Sawk",
            "082 Golett",
            "083 Golurk",
            "084 Grimer",
            "085 Muk",
            "086 Sneasel",
            "087 Weavile",
            "088 Honchkrow V",
            "089 Spiritomb",
            "090 Purrloin",
            "091 Liepard",
            "092 Impidimp",
            "093 Morgrem",
            "094 Grimmsnarl",
            "095 Morpeko V",
            "096 Aggron V",
            "097 Aggron VMAX",
            "098 Wormadam",
            "099 Probopass",
            "100 Heatran",
            "101 Escavalier",
            "102 Klink",
            "103 Klang",
            "104 Klinklang",
            "105 Zamazenta V",
            "106 Flygon V",
            "107 Gible",
            "108 Gabite",
            "109 Garchomp",
            "110 Axew",
            "111 Fraxure",
            "112 Haxorus",
            "113 Druddigon",
            "114 Dracovish V",
            "115 Farfetch'd",
            "116 Castform",
            "117 Starly",
            "118 Staravia",
            "119 Staraptor",
            "120 Bidoof",
            "121 Bibarel",
            "122 Arceus V",
            "123 Arceus VSTAR",
            "124 Minccino",
            "125 Cinccino",
            "126 Tornadus",
            "127 Hawlucha",
            "128 Drampa V",
            "129 Acerola's Premonition",
            "130 Barry",
            "131 Blunder Policy",
            "132 Boss's Orders",
            "133 Café Master",
            "134 Cheren's Care",
            "135 Choice Belt",
            "136 Cleansing Gloves",
            "137 Collapsed Stadium",
            "138 Cynthia's Ambition",
            "139 Fresh Water Set",
            "140 Friends in Galar",
            "141 Gloria",
            "142 Hunting Gloves",
            "143 Kindler",
            "144 Magma Basin",
            "145 Marnie's Pride",
            "146 Pot Helmet",
            "147 Professor's Research",
            "148 Roseanne's Backup",
            "149 Team Yell's Cheer",
            "150 Ultra Ball",
            "151 Double Turbo Energy",
            "152 Shaymin V",
            "153 Charizard V",
            "154 Charizard V",
            "155 Lumineon V",
            "156 Lumineon V",
            "157 Pikachu V",
            "158 Raichu V",
            "159 Granbull V",
            "160 Whimsicott V",
            "161 Honchkrow V",
            "162 Honchkrow V",
            "163 Zamazenta V",
            "164 Flygon V",
            "165 Arceus V",
            "166 Arceus V",
            "167 Barry",
            "168 Cheren's Care",
            "169 Cynthia's Ambition",
            "170 Kindler",
            "171 Marnie's Pride",
            "172 Roseanne's Backup",
            "173 Shaymin VSTAR",
            "174 Charizard VSTAR",
            "175 Whimsicott VSTAR",
            "176 Arceus VSTAR",
            "177 Cheren's Care",
            "178 Cynthia's Ambition",
            "179 Kindler",
            "180 Roseanne's Backup",
            "181 Galarian Articuno V",
            "182 Galarian Zapdos V",
            "183 Galarian Moltres V",
            "184 Arceus VSTAR",
            "185 Magma Basin",
            "186 Ultra Ball",
            //Trainer Gallery (TG)
            "TG1  Flareon",
            "TG2  Vaporeon",
            "TG3  Octillery",
            "TG4  Jolteon",
            "TG5  Zekrom",
            "TG6  Dusknoir",
            "TG7  Dedenne",
            "TG8  Alcremie",
            "TG9  Ariados",
            "TG10 Houndoom",
            "TG11 Eevee",
            "TG12 Oranguru",
            "TG13 Boltund V",
            "TG14 Sylveon V",
            "TG15 Sylveon VMAX",
            "TG16 Mimikyu V",
            "TG17 Mimikyu VMAX",
            "TG18 Single Strike Urshifu V",
            "TG19 Single Strike Urshifu VMAX",
            "TG20 Rapid Strike Urshifu V",
            "TG21 Rapid Strike Urshifu VMAX",
            "TG22 Umbreon V",
            "TG23 Umbreon VMAX",
            "TG24 Acerola's Premonition",
            "TG25 Cafe Master",
            "TG26 Gloria",
            "TG27 Rapid Strike Style Mustard",
            "TG28 Single Strike Style Mustard",
            "TG29 Single Strike Urshifu VMAX",
            "TG30 Rapid Strike Urshifu VMAX"
    );

    public static List<String> getCardList() {
        return cl_brilliant_stars;
    }
}
